tsukuba:
  target: default
  outputs:
    default:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: tsukuba
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
      attach:
        - path: "md:tsukuba"
          alias: tsukuba
          is_ducklake: true
    local:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: tsukuba
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
      attach:
        - path: "md:dev_tsukuba"
          alias: tsukuba
          is_ducklake: true
